### ISSUE TITLE
下载demo apk装上试了下有点问题

### ISSUE THREAD

**Issue by ysh329** [allonli/mobile-deep-learning#1]
下载demo apk装上试了下有点问题，安装好第一次打开可以调用摄像头并对拍摄的照片调用模型识别，但是第二次点击take photo没有反应了，是不是有bug还是我操作不对呀

![image](https://user-images.githubusercontent.com/7320657/53788953-2878ec80-3f5e-11e9-8011-ece559d00485.png)

**Comment by allonli** [comment]
建议使用 Paddle-Mobile 中的 Demo:
https://github.com/PaddlePaddle/paddle-mobile
